# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  type: redirect
  to: "https://www.{default}/"

"https://admin.{default}/":
  type: upstream
  upstream: "app:http"

"https://www.{default}/":
  type: upstream
  upstream: "app:http"

"https://beta.{default}/":
  type: upstream
  upstream: "app:http"


